/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphicaluserinterface;

import javax.swing.JOptionPane;
import model.Barang;

/**
 *
 * @author user1
 */
public class FormDataBarang extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDataBarang.class.getName());

    /**
     * Creates new form FormDataBarang
     */
    public FormDataBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroupKondisi = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldKode = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonTampil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUmur = new javax.swing.JTextField();
        jSpinnerJuara = new javax.swing.JSpinner();
        jLabelTotalJuara = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelJenis = new javax.swing.JLabel();
        jComboBoxJenis = new javax.swing.JComboBox<>();
        jRadioButtonSehat = new javax.swing.JRadioButton();
        jRadioButtonLumayanSehat = new javax.swing.JRadioButton();
        jRadioButtonKurangSehat = new javax.swing.JRadioButton();
        jRadioButtonSakit = new javax.swing.JRadioButton();
        jButtonKeluar = new javax.swing.JButton();
        jButtonBersih = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALBERT.exe");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("DATA UMA MUSUME");

        jLabel2.setText("Nama Uma");

        jLabel3.setText("Kode Uma");

        jTextFieldKode.addActionListener(this::jTextFieldKodeActionPerformed);

        jTextFieldNama.addActionListener(this::jTextFieldNamaActionPerformed);

        jButtonTampil.setText("T A M P I L");
        jButtonTampil.addActionListener(this::jButtonTampilActionPerformed);

        jLabel4.setText("Umur Uma");

        jTextFieldUmur.setText(" ");

        jLabelTotalJuara.setText("Total Menang");

        jLabel6.setText("Harga Uma");

        jLabel5.setText("Kondisi Uma");

        jLabelJenis.setText("Jenis Uma");

        jComboBoxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mile", "Medium", "Sprint", "Long" }));

        buttonGroupKondisi.add(jRadioButtonSehat);
        jRadioButtonSehat.setText("Sehat");
        jRadioButtonSehat.addActionListener(this::jRadioButtonSehatActionPerformed);

        buttonGroupKondisi.add(jRadioButtonLumayanSehat);
        jRadioButtonLumayanSehat.setText("Lumayan Sehat");

        buttonGroupKondisi.add(jRadioButtonKurangSehat);
        jRadioButtonKurangSehat.setText("Kurang Sehat");

        buttonGroupKondisi.add(jRadioButtonSakit);
        jRadioButtonSakit.setText("Sakit");

        jButtonKeluar.setText("X");
        jButtonKeluar.addActionListener(this::jButtonKeluarActionPerformed);

        jButtonBersih.setText("C L E A R");
        jButtonBersih.addActionListener(this::jButtonBersihActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelJenis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelTotalJuara)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerJuara, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(149, 149, 149))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jTextFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(82, 82, 82)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonKurangSehat)
                                            .addComponent(jRadioButtonSehat))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonLumayanSehat)
                                            .addComponent(jRadioButtonSakit))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jButtonKeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTampil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBersih)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKeluar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerJuara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalJuara))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonSehat)
                    .addComponent(jRadioButtonLumayanSehat))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonKurangSehat)
                    .addComponent(jRadioButtonSakit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJenis)
                    .addComponent(jComboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTampil)
                    .addComponent(jButtonBersih))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodeActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTampilActionPerformed
        String kode = jTextFieldKode.getText();
        String nama = jTextFieldNama.getText();
        String umur = jTextFieldUmur.getText();
        int harga = Integer.parseInt(jTextFieldHarga.getText());
        int juara = (Integer)jSpinnerJuara.getValue();
        String jenis = jComboBoxJenis.getSelectedItem().toString();
        String kondisi = "";
        if(jRadioButtonSehat.isSelected())
           kondisi = "Uma Sehat";
        else if(jRadioButtonSakit.isSelected())
            kondisi = "Uma Sakit";
        else if(jRadioButtonLumayanSehat.isSelected())
            kondisi = "Uma Lumayan Sehat";
        else if(jRadioButtonKurangSehat.isSelected())
            kondisi = "Uma Kurang Sehat";
        jRadioButtonSehat.setSelected(true);
        Barang uma = new Barang(kode, nama, umur, juara, harga);
        String pesan = "Kode Uma\t: " + uma.getKode() + 
                "\nNama Uma\t: " + uma.getNama() + 
                "\nUmur Uma\t: " + uma.getUmur() +
                "\nTotal Menang\t: " + uma.getJuara() + 
                "\nHarga Uma\t: " + uma.getHarga() +
                "\nKondisi Uma\t: " + kondisi +
                "\nJenis Uma\t: " + jenis +
                "\nTotal Keuntungan\t: " + uma.getKeuntungan();
        JOptionPane.showMessageDialog(null, pesan, "INFORMASI", JOptionPane.INFORMATION_MESSAGE);       
    }//GEN-LAST:event_jButtonTampilActionPerformed

    private void jRadioButtonSehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSehatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSehatActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jButtonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBersihActionPerformed
       jTextFieldHarga.setText("");
       jTextFieldKode.setText("");
    jTextFieldNama.setText("");
jComboBoxJenis.setSelectedIndex(0);
jSpinnerJuara.setValue(1);
jTextFieldUmur.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDataBarang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupKondisi;
    private javax.swing.JButton jButtonBersih;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonTampil;
    private javax.swing.JComboBox<String> jComboBoxJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelJenis;
    private javax.swing.JLabel jLabelTotalJuara;
    private javax.swing.JRadioButton jRadioButtonKurangSehat;
    private javax.swing.JRadioButton jRadioButtonLumayanSehat;
    private javax.swing.JRadioButton jRadioButtonSakit;
    private javax.swing.JRadioButton jRadioButtonSehat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerJuara;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldKode;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldUmur;
    // End of variables declaration//GEN-END:variables
}
